/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package uasoop;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FDosen extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    DbKoneksi koneksi = new DbKoneksi();
    /**
     * Creates new form FDosen
     */
    public FDosen() {
        initComponents();
        this.inittable();
        this.getdata();
    }
    
    private void inittable(){
        model = new DefaultTableModel();
        tbDosen.setModel(model);
        model.addColumn("NPWP");
        model.addColumn("Nama Dosen");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jenjang Pnedidikan");
        
    }
    private void tampildata(String sql){
        try{
            Statement stmt = koneksi.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("Terjadi Kendala pada query");
        }
    }
    
    private void getdata(){
        String sql = "Select Npwp,Nama,Jk,Jenjang FROM dosen;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.tampildata(sql);
            while(this.rs.next()){
                Object[] obj = new Object[4];
                obj[0] = this.rs.getString("Npwp");
                obj[1] = this.rs.getString("Nama");
                obj[2] = this.rs.getString("Jenjang");
                String txJK = this.rs.getString("Jk");
                if(txJK.equals("L")){
                    obj[3] = "Laki-Laki";
                }else{
                    obj[3] = "Perempuan";
                }
                model.addRow(obj);
            }
        }catch(Exception e){
        }
    }
    
    private boolean updatedata(String SQL){
        boolean hsl = false;
        try{
            Statement stmt = koneksi.koneksi().createStatement();
            stmt.executeUpdate(SQL);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDosen = new javax.swing.JTable();
        lbSub = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNpwp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JkL = new javax.swing.JRadioButton();
        JkP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tJenjang = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabel1.setText("Data Dosen");

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tbDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDosen);

        lbSub.setText("Detail Data");

        jLabel3.setText("NPWP Dosen");

        jLabel4.setText("Nama Dosen");

        jLabel5.setText("Jenis Kelamin");

        JkL.setText("Laki-laki");

        JkP.setText("Perempuan");
        JkP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkPActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenjang Pendidikan");

        tJenjang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenjang", "S1", "S2", "S3" }));

        btnSimpan.setText("Simpan Data");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Data");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Data");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Tutup Form");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(tNpwp)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JkL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JkP))
                            .addComponent(jLabel6)
                            .addComponent(tJenjang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                                .addComponent(btnCancel)
                                .addGap(27, 27, 27)
                                .addComponent(btnClose))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTambah))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSub)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSub)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNpwp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JkL)
                            .addComponent(JkP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tJenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClose)
                    .addComponent(btnCancel))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JkPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JkPActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String NPWP = this.tNpwp.getText();
        String NAMA = this.tNama.getText();
        String JEN = this.tJenjang.getSelectedItem().toString();
        String JKEL = "L";
        if(this.JkP.isSelected()){
            JKEL = "P";
        }
        String SQLUpdate = "UPDATE dosen SET Nama='"+NAMA+"', Jenjang='"+JEN+"', Jk='"+JKEL+"' WHERE Npwp='"+NPWP+"';";
        if(this.updatedata(SQLUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
         this.btnTambah.setEnabled(false);
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
        this.btnClose.setEnabled(false);
        this.btnSimpan.setEnabled(true);
        this.btnCancel.setVisible(true);
        
        this.tNpwp.setText("");
        this.tNama.setText("");
        this.tJenjang.setSelectedIndex(0);
        
        this.lbSub.setText("Tambah data DOSEN");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.btnClose.setEnabled(true);
        this.btnTambah.setEnabled(true);
        this.btnSimpan.setEnabled(false);
        this.btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tbDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDosenMouseClicked
        this.tNpwp.setText( model.getValueAt(tbDosen.getSelectedRow(), 0).toString());
        this.tNama.setText( model.getValueAt(tbDosen.getSelectedRow(), 1).toString());
        this.tJenjang.setSelectedItem(model.getValueAt(tbDosen.getSelectedRow(), 2).toString());
        String txJK = model.getValueAt(tbDosen.getSelectedRow(), 3).toString();
        if(txJK.equals("Perempuan")){
            this.JkP.setSelected(true);
        }else{
            this.JkL.setSelected(true);
        }
        
        this.lbSub.setText("Edit Data "+this.tNama.getText());
        this.btnSimpan.setEnabled(false);
        this.btnUpdate.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }//GEN-LAST:event_tbDosenMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String NPWP = this.tNpwp.getText();
        String NAMA = this.tNama.getText();
        
        int opsi = JOptionPane.showConfirmDialog(null,"Yakin akan menghapus data dari "+NAMA+"("+NPWP+")?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION){
            String SQLDelete = "DELETE FROM dosen WHERE Npwp='"+NPWP+"';";
            if(this.updatedata(SQLDelete)){
                this.getdata();
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         String NPWP = this.tNpwp.getText();
        String NAMA = this.tNama.getText();
        String JEN = this.tJenjang.getSelectedItem().toString();
        String JKEL = "L";
        if(this.JkP.isSelected()){
            JKEL = "P";
        }
        String SQLInsert = "INSERT INTO dosen(Npwp, Nama, Jk, Jenjang) VALUES('"+NPWP+"','"+NAMA+"','"+JKEL+"','"+JEN+"');";
        if(this.updatedata(SQLInsert)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.btnSimpan.setEnabled(false);
        this.btnCancel.setVisible(false);
        this.btnClose.setEnabled(true);
        this.btnTambah.setEnabled(true);
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JkL;
    private javax.swing.JRadioButton JkP;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbSub;
    private javax.swing.JComboBox<String> tJenjang;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNpwp;
    private javax.swing.JTable tbDosen;
    // End of variables declaration//GEN-END:variables
}
