package uasoop;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FMhs extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    DbKoneksi koneksi = new DbKoneksi();
    /**
     * Creates new form tbMhs
     */
    public FMhs() {
        initComponents();
        this.inittable();
        this.getdata();
    }
    
     private void inittable(){
        model = new DefaultTableModel();
        TbMhs.setModel(model);
        model.addColumn("NIM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Tgl Lahir");
        model.addColumn("Jurusan");
        model.addColumn("Jenis Kelamin");
    }
    private void tampildata(String sql){
        try{
            Statement stmt = koneksi.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("Terjadi Kendala pada query");
        }
    }
    
    private void getdata(){
        String sql = "Select Nim, Nama, Tgl, Jurusan, Jk FROM mhs;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.tampildata(sql);
            while(this.rs.next()){
                Object[] obj = new Object[5];
                obj[0] = this.rs.getString("Nim");
                obj[1] = this.rs.getString("Nama");
                obj[2] = this.rs.getString("Tgl");
                obj[3] = this.rs.getString("Jurusan");
                String txJK = this.rs.getString("Jk");
                if(txJK.equals("L")){
                    obj[4] = "Laki-Laki";
                }else{
                    obj[4] = "Perempuan";
                }
                model.addRow(obj);
            }
        }catch(Exception e){
        }
    }
    
    private boolean updatedata(String SQL){
        boolean hsl = false;
        try{
            Statement stmt = koneksi.koneksi().createStatement();
            stmt.executeUpdate(SQL);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbMhs = new javax.swing.JTable();
        lbSub = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tNim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JkL = new javax.swing.JRadioButton();
        JkP = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tTgl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tJurusan = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Data Mahasiswa");

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        TbMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbMhs);

        lbSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSub.setText("Detail Data");

        jLabel1.setText("NIM");

        jLabel3.setText("Nama Mahasiswa");

        jLabel4.setText("Jenis Kelamin");

        JkL.setText("Laki-laki");
        JkL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkLActionPerformed(evt);
            }
        });

        JkP.setText("Perempuan");
        JkP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkPActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal Lahir");

        tTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTglActionPerformed(evt);
            }
        });

        jLabel6.setText("Jurusan");

        tJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jurusan", "MTI", "DGM", "KAB", "SK" }));

        btnSimpan.setText("Simpan Data");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Data");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus Data");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Tutup Form");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSub, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(tNim)
                                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JkL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JkP)))
                                        .addGap(94, 94, 94)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(tJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSub)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JkL)
                            .addComponent(JkP)
                            .addComponent(tJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClose)
                    .addComponent(btnCancel))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        this.btnTambah.setEnabled(false);
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
        this.btnClose.setEnabled(false);
        this.btnSimpan.setEnabled(true);
        this.btnCancel.setVisible(true);
        
        this.tNim.setText("");
        this.tNama.setText("");
        this.tTgl.setText("");
        this.tJurusan.setSelectedIndex(0);
        
        this.lbSub.setText("Tambah data Mahasiswa");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void JkLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JkLActionPerformed

    private void JkPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JkPActionPerformed

    private void tTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTglActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String NIM = this.tNim.getText();
        String NAMA = this.tNama.getText();
        String TGL = this.tTgl.getText();
        String JUR = this.tJurusan.getSelectedItem().toString();
        String JKEL = "L";
        if(this.JkP.isSelected()){
            JKEL = "P";
        }
        String SQLUpdate = "UPDATE mhs SET Nama='"+NAMA+"', Jurusan='"+JUR+"', Jk='"+JKEL+"', Tgl='"+TGL+"' WHERE Nim='"+NIM+"';";
        if(this.updatedata(SQLUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void TbMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMhsMouseClicked
        this.tNim.setText( model.getValueAt(TbMhs.getSelectedRow(), 0).toString());
        this.tNama.setText( model.getValueAt(TbMhs.getSelectedRow(), 1).toString());
        this.tTgl.setText( model.getValueAt(TbMhs.getSelectedRow(), 2).toString());
        this.tJurusan.setSelectedItem(model.getValueAt(TbMhs.getSelectedRow(), 3).toString());
        String txJK = model.getValueAt(TbMhs.getSelectedRow(), 4).toString();
        if(txJK.equals("Perempuan")){
            this.JkP.setSelected(true);
        }else{
            this.JkL.setSelected(true);
        }
        
        this.lbSub.setText("Edit Data "+this.tNama.getText());
        this.btnSimpan.setEnabled(false);
        this.btnUpdate.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }//GEN-LAST:event_TbMhsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String NIM = this.tNim.getText();
        String NAMA = this.tNama.getText();
        
        int opsi = JOptionPane.showConfirmDialog(null,"Yakin akan menghapus data dari "+NAMA+"("+NIM+")?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION){
            String SQLDelete = "DELETE FROM mhs WHERE Nim='"+NIM+"';";
            if(this.updatedata(SQLDelete)){
                this.getdata();
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.btnClose.setEnabled(true);
        this.btnTambah.setEnabled(true);
        this.btnSimpan.setEnabled(false);
        this.btnCancel.setVisible(false);

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String NIM = this.tNim.getText();
        String NAMA = this.tNama.getText();
        String TGL = this.tTgl.getText();
        String JUR = this.tJurusan.getSelectedItem().toString();
        String JKEL = "L";
        if(this.JkP.isSelected()){
            JKEL = "P";
        }
        String SQLInsert = "INSERT INTO mhs(Nim,Nama,Tgl,Jk,Jurusan) VALUES('"+NIM+"','"+NAMA+"','"+TGL+"','"+JKEL+"','"+JUR+"');";
        if(this.updatedata(SQLInsert)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.btnSimpan.setEnabled(false);
        this.btnCancel.setVisible(false);
        this.btnClose.setEnabled(true);
        this.btnTambah.setEnabled(true);
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JkL;
    private javax.swing.JRadioButton JkP;
    private javax.swing.JTable TbMhs;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbSub;
    private javax.swing.JComboBox<String> tJurusan;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNim;
    private javax.swing.JTextField tTgl;
    // End of variables declaration//GEN-END:variables
}
