package uasoop;

public class FUtama extends javax.swing.JFrame {
    FMhs fm;
    FDosen fd;
    FMatkul fmat;
    
    public FUtama() {
        this.setSize(1000,550);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskutama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MFIle = new javax.swing.JMenu();
        MExit = new javax.swing.JMenuItem();
        MMHS = new javax.swing.JMenu();
        MDosen = new javax.swing.JMenu();
        MMatkul = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskutamaLayout = new javax.swing.GroupLayout(dskutama);
        dskutama.setLayout(dskutamaLayout);
        dskutamaLayout.setHorizontalGroup(
            dskutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );
        dskutamaLayout.setVerticalGroup(
            dskutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        getContentPane().add(dskutama, java.awt.BorderLayout.CENTER);

        MFIle.setText("File");

        MExit.setText("Exit");
        MExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MExitActionPerformed(evt);
            }
        });
        MFIle.add(MExit);

        jMenuBar1.add(MFIle);

        MMHS.setText("DataMahasiswa");
        MMHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMHSMouseClicked(evt);
            }
        });
        MMHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMHSActionPerformed(evt);
            }
        });
        jMenuBar1.add(MMHS);

        MDosen.setText("DataDosen");
        MDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MDosenMouseClicked(evt);
            }
        });
        MDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDosenActionPerformed(evt);
            }
        });
        jMenuBar1.add(MDosen);

        MMatkul.setText("DataMatakuliah");
        MMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMatkulMouseClicked(evt);
            }
        });
        jMenuBar1.add(MMatkul);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MExitActionPerformed

    private void MMHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMHSActionPerformed
        
    }//GEN-LAST:event_MMHSActionPerformed

    private void MMHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMHSMouseClicked
        if(fm==null || fm.isClosed() ){
            fm = new FMhs();
            dskutama.add(fm);
            fm.setLocation(this.getWidth()/2 - fm.getWidth()/2, this.getHeight()/2-fm.getHeight()/2);
            fm.setVisible(true);
            fd.dispose();
            fmat.dispose();
        }else{
            fm.setVisible(true);
        }
    }//GEN-LAST:event_MMHSMouseClicked

    private void MDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDosenActionPerformed
//        
    }//GEN-LAST:event_MDosenActionPerformed

    private void MDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MDosenMouseClicked
        if(fd==null || fd.isClosed() ){
            fd = new FDosen();
            dskutama.add(fd);
            fd.setLocation(this.getWidth()/2 - fd.getWidth()/2, this.getHeight()/2-fd.getHeight()/2);
            fd.setVisible(true);
            fm.dispose();
            fmat.dispose();
        }else{
            fd.setVisible(true);
        }
    }//GEN-LAST:event_MDosenMouseClicked

    private void MMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMatkulMouseClicked
        if(fmat==null || fmat.isClosed() ){
            fmat = new FMatkul();
            dskutama.add(fmat);
            fmat.setLocation(this.getWidth()/2 - fmat.getWidth()/2, this.getHeight()/2-fmat.getHeight()/2);
            fmat.setVisible(true);
            fd.dispose();
            fm.dispose();
        }else{
            fm.setVisible(true);
        }
    }//GEN-LAST:event_MMatkulMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MDosen;
    private javax.swing.JMenuItem MExit;
    private javax.swing.JMenu MFIle;
    private javax.swing.JMenu MMHS;
    private javax.swing.JMenu MMatkul;
    private javax.swing.JDesktopPane dskutama;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
